In [2]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR 

In [3]:
df = pd.read_csv('Sales_clean_data.csv')


In [4]:
df

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50
...,...,...,...,...,...,...,...
95,512878119,888,109.28,35.84,97040.64,31825.92,65214.72
96,810711038,6267,9.33,6.92,58471.11,43367.64,15103.47
97,728815257,1485,154.06,90.93,228779.10,135031.05,93748.05
98,559427106,5767,81.73,56.67,471336.91,326815.89,144521.02


In [5]:
df.head()

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50


In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   order_id       100 non-null    int64  
 1   units_sold     100 non-null    int64  
 2   unit_price     100 non-null    float64
 3   unit_cost      100 non-null    float64
 4   total_revenue  100 non-null    float64
 5   total_cost     100 non-null    float64
 6   total_profit   100 non-null    float64
dtypes: float64(5), int64(2)
memory usage: 5.6 KB


In [7]:
if 'order_date' not in df.columns:
    df['order_date'] = np.random.randint(1, 31, size=len(df))

In [8]:
df

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit,order_date
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50,24
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36,25
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75,19
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82,2
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50,3
...,...,...,...,...,...,...,...,...
95,512878119,888,109.28,35.84,97040.64,31825.92,65214.72,23
96,810711038,6267,9.33,6.92,58471.11,43367.64,15103.47,10
97,728815257,1485,154.06,90.93,228779.10,135031.05,93748.05,24
98,559427106,5767,81.73,56.67,471336.91,326815.89,144521.02,10


In [9]:
x=df.drop("order_date", axis=1)

In [10]:
y=df[['order_date']]

In [11]:
x

,order_id,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,669165933,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,963881480,2804,205.70,117.11,576782.80,328376.44,248406.36
2,341417157,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,514321792,8102,9.33,6.92,75591.66,56065.84,19525.82
4,115456712,5062,651.21,524.96,3296425.02,2657347.52,639077.50
...,...,...,...,...,...,...,...
95,512878119,888,109.28,35.84,97040.64,31825.92,65214.72
96,810711038,6267,9.33,6.92,58471.11,43367.64,15103.47
97,728815257,1485,154.06,90.93,228779.10,135031.05,93748.05
98,559427106,5767,81.73,56.67,471336.91,326815.89,144521.02


In [12]:
y

,order_date
0,24
1,25
2,19
3,2
4,3
...,...
95,23
96,10
97,24
98,10


In [13]:
y['order_date'].unique()

array([24, 25, 19,  2,  3,  7, 27, 28,  5,  9,  8, 13, 29, 23, 12, 18, 21,
       15, 30, 17, 20, 10,  6,  1, 16, 26, 22, 14, 11,  4], dtype=int32)

In [14]:
y['order_date'].value_counts()

order_date
24    6
2     6
25    5
3     5
7     5
28    5
13    5
21    5
30    5
9     4
23    4
12    4
18    4
15    4
10    4
22    4
19    3
27    3
8     3
29    3
16    2
26    2
4     2
5     1
17    1
20    1
6     1
1     1
14    1
11    1
Name: count, dtype: int64

In [15]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((80, 7), (80, 1), (20, 7), (20, 1))

In [16]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
dtc=DecisionTreeClassifier(criterion='entropy')

In [17]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)
dtc.fit(x_train, y_train)


,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'entropy'
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",42
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsampl

In [18]:
y_pred = dtc.predict(x_test)
y_pred[:10]


array([18, 30, 21,  7, 28, 27,  8,  3,  3, 22], dtype=int32)

In [19]:
dtc.predict([[115456712,  5062,  651.21,  524.96,  3296425.02,  2657347.52,  639077.50]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([3], dtype=int32)

In [20]:
print("Train Score:", dtc.score(x_train, y_train))
print("Test Score:", dtc.score(x_test, y_test))


Train Score: 1.0
Test Score: 0.1


In [21]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': 42,
 'splitter': 'best'}

In [22]:
sm=LinearRegression()

In [23]:
sm.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1, 7)","[[ 0.,-0., 0.,..., 0., 0.,-0.]]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](7,)","['order_id','units_sold','unit_price',...,'total_revenue','total_cost', 'total_profit']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.","ndarray[float64](1,)",[17.12]
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,7
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int,4


In [24]:
print(sm.score(x_train, y_train))
print(sm.score(x_test, y_test))

0.01591553071392815
-0.08202230552272227


In [25]:
import joblib
joblib.dump(sm, "model.lb")

['model.lb']

In [26]:
model=joblib.load('model.lb')

In [27]:
model.predict([[512878119,  888,  109.28,  35.84,  97040.64,  31825.92,  65214.72]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[17.57313539]])

In [28]:
sm=SVC()
sm.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide <scores_probabilities>`...deprecated:: 1.9 The `probability` parameter is deprecated and will be removed in 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`.",'deprecated'
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [29]:
print(sm.score(x_train, y_train))
print(sm.score(x_test, y_test))

0.0875
0.05


In [30]:
sm=SVR()
sm.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm.If none is given, 'rbf' will be used. If a callable is given it isused to precompute the kernel matrix.For an intuitive visualization of different kernel typessee :ref:`sphx_glr_auto_examples_svm_plot_svm_regression.py`",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.The penalty is a squared l2. For an intuitive visualization of theeffects of scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"epsilon epsilon: float, default=0.1Epsilon in the epsilon-SVR model. It specifies the epsilon-tubewithin which no penalty is associated in the training loss functionwith points predicted within a distance epsilon from the actualvalue. Must be non-negative.",0.1
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False
,"max_iter max_iter: int, default=-1Hard limit on iterations within solver, or -1 for no limit.",-1


In [31]:
print(sm.score(x_train, y_train))
print(sm.score(x_test, y_test))

-0.007635654352451615
0.012496774213838657


In [32]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,

In [33]:
print(y_test.iloc[:, 0].unique())

[26 30 11  9  6  3 18  2  5 24 28 19 16 13 22 27]


In [34]:
print(len(y_test.iloc[:,0].unique()))

16


In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test.iloc[:,0], y_pred))

              precision    recall  f1-score   support

           2       0.00      0.00      0.00         1
           3       0.33      0.50      0.40         2
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          19       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         3
          26       0.00    

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

In [36]:
y_binary = (df['order_date'] > 15).astype(int)
x_train_b, x_test_b, y_train_b, y_test_b = train_test_split(
    x, y_binary, test_size=0.2, random_state=42 )
dtc_b = DecisionTreeClassifier(criterion='entropy', random_state=42)
dtc_b.fit(x_train_b, y_train_b)
y_pred_b = dtc_b.predict(x_test_b)

In [37]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test_b, y_pred_b)
print(cm)
print("\nClassification Report:\n")
print(classification_report(y_test_b, y_pred_b))


[[2 6]
 [5 7]]

Classification Report:

              precision    recall  f1-score   support

           0       0.29      0.25      0.27         8
           1       0.54      0.58      0.56        12

    accuracy                           0.45        20
   macro avg       0.41      0.42      0.41        20
weighted avg       0.44      0.45      0.44        20



In [38]:
#  MSE
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)

127.65

In [39]:
# MSE & MAE
from sklearn.metrics import mean_absolute_error, mean_squared_error
print("Mean_squared_error:-",mean_squared_error(y_test, y_pred))
print("Mean_absolute_error:-",mean_absolute_error(y_test, y_pred))

Mean_squared_error:- 127.65
Mean_absolute_error:- 8.15


In [40]:
rmse=np.sqrt(mean_squared_error(y_test, y_pred))

In [41]:
rmse

np.float64(11.298229949863828)

In [42]:
rmse=np.sqrt(mean_absolute_error(y_test, y_pred))

In [43]:
rmse

np.float64(2.8548204847240397)