In [2]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print("Matrix of A:")
print(A)
transpose_A = A.T
print("\nTranspose of A:")
print(transpose_A)
det_A = np.linalg.det(A)
print("\nDeterminant of A:")
print(det_A)
rank_A = np.linalg.matrix_rank(A)
print("\nRank of A:")
print(rank_A)
if det_A != 0:
    inverse_A = np.linalg.inv(A)
    print("\nInverse of A:")
    print(inverse_A)
else:
    print("\nInverse does not exist (determinant is zero).")

Matrix of A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of A:
0.0

Rank of A:
2

Inverse does not exist (determinant is zero).
