In [1]:
pip install numpy

     -------------------------------------- 12.6/12.6 MB 668.3 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
np.__version__

'2.4.6'

In [9]:
lst = list[range(1,20)]

In [10]:
lst = [1,2,3,4,5]
arr = np.array(lst)
type(arr)

numpy.ndarray

In [11]:
arr = np.array(lst)

In [13]:
arr=np.array([1,2,3,4,5,6,8,7,10,12])

In [14]:
arr=np.array([range(1,20)])
type(arr)

numpy.ndarray

In [21]:

arr=np.arange(1,21)
print(type(arr))

<class 'numpy.ndarray'>


In [16]:

arr=np.zeros(10)

In [17]:
arr=np.ones(10)

In [ ]:
arr

In [19]:
arr=np.zeros((5,10))
print(arr.ndim)

2


In [ ]:
arr = np.linspace(1,10,5)
print(arr)
print(type(arr))

In [ ]:
arr = np.arrange(0,30)

In [25]:


arr = np.arange(1, 21)

arr = arr.reshape(4, 5)

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [27]:

arr = np.random.randint(1, 5, 10)

print(arr)

[2 2 3 1 2 3 2 2 3 1]


In [ ]:
arr = np.random.random(10)

In [29]:
arr

array([0.89122288, 0.19769078, 0.34617551, 0.9377743 , 0.11654442,
       0.84558432, 0.91890211, 0.64102739, 0.31212436, 0.9343851 ])

In [31]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [33]:
print("Numeber of dim:-",arr.ndim)
print("Shape of array:-",arr.shape)
print("Data type of item:-",arr.dtype)
print("Size of array:-",arr.size)

Numeber of dim:- 2
Shape of array:- (12, 5)
Data type of item:- int64
Size of array:- 60


In [34]:
lst = [[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [35]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:

arr = np.arange(1, 61).reshape(6, 10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [37]:
print("Numeber of dim:-",arr.ndim)
print("Shape of array:-",arr.shape)
print("Data type of item:-",arr.dtype)
print("Size of array:-",arr.size)

Numeber of dim:- 2
Shape of array:- (6, 10)
Data type of item:- int64
Size of array:- 60


In [38]:
arr.T

array([[ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55],
       [ 6, 16, 26, 36, 46, 56],
       [ 7, 17, 27, 37, 47, 57],
       [ 8, 18, 28, 38, 48, 58],
       [ 9, 19, 29, 39, 49, 59],
       [10, 20, 30, 40, 50, 60]])

In [39]:
arr[0,0]

np.int64(1)

In [41]:
arr[-1,-2]

np.int64(59)

In [43]:
arr[1:4, 1:]


array([[12, 13, 14, 15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27, 28, 29, 30],
       [32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [44]:
arr[:, 4:6]

array([[ 5,  6],
       [15, 16],
       [25, 26],
       [35, 36],
       [45, 46],
       [55, 56]])

In [ ]:
arr[-1,-1]

In [10]:
print("Numeber of dim:-",arr.ndim)
print("Shape of array:-",arr.shape)
print("Data type of item:-",arr.dtype)
print("Size of array:-",arr.size)

Numeber of dim:- 3
Shape of array:- (5, 15, 3)
Data type of item:- int64
Size of array:- 225


In [5]:
arr = np.arange(225).reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [6]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [7]:
arr[:, 2:4, :]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [8]:
arr[0:5, 2:4, 0:3]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]],

       [[141, 142, 143],
        [144, 145, 146]],

       [[186, 187, 188],
        [189, 190, 191]]])

In [9]:
arr[0:5, 14:15, 0:3]

array([[[ 42,  43,  44]],

       [[ 87,  88,  89]],

       [[132, 133, 134]],

       [[177, 178, 179]],

       [[222, 223, 224]]])

In [11]:
print("Numeber of dim:-",arr.ndim)
print("Shape of array:-",arr.shape)
print("Data type of item:-",arr.dtype)
print("Size of array:-",arr.size)

Numeber of dim:- 3
Shape of array:- (5, 15, 3)
Data type of item:- int64
Size of array:- 225


In [12]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([9,10,11,12,13,14,15,16])
print(arr1*arr2)

[  9  20  33  48  65  84 105 128]


In [13]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [14]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]


In [16]:
arr1.sort()
arr1

array([10, 20, 30, 40])